apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-outbox-connector
  namespace: cache-app
data:
  connector.json: |
    {
      "name": "mysql-outbox-connector",
      "config": {

        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "tasks.max": "1",

        "database.hostname": "customer-mysql",
        "database.port": "3306",
        "database.user": "${DB_USERNAME}",
        "database.password": "${DB_PASSWORD}",

        "database.server.id": "184054",
        "topic.prefix": "customerdb",

        "table.include.list": "customer_db.outbox_event",

        "schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
        "schema.history.internal.kafka.topic": "schemahistory.customer",

        "snapshot.mode": "initial",

        "transforms": "outbox",
        "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",

        "transforms.outbox.route.by.field": "aggregate_type",
        "transforms.outbox.route.topic.replacement": "customer_topic",

        "transforms.outbox.table.field.event.id": "event_id",
        "transforms.outbox.table.field.event.key": "aggregate_id",
        "transforms.outbox.table.field.event.payload": "payload",

        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false"
      }
    }
