apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: cache-app-v2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  DB_USERNAME: user
  DB_PASSWORD: password
  DB_ROOT_PASSWORD: root