{{- if .Values.customerService.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
    name: customer-service-config
    namespace: {{ .Values.namespace }}

    annotations:
        argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.customerServiceConfigMap }}"

data:
    SPRING_PROFILES_ACTIVE: "{{ .Values.activeProfiles }}"

    DB_URL: "jdbc:mysql://{{ .Values.mysql.hostname }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}"

    SPRING_REDIS_HOST: "{{ .Values.redis.hostname }}"

    REDIS_PORT: "{{ .Values.redis.port }}"

    KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.bootstrapServers }}"
  {{- end }}