apiVersion: v1
kind: Secret

metadata:
  name: customer-service-secret
  namespace: {{ .Values.namespace }}

  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.customerServiceSecret }}"

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.mysql.username | quote }}

  DB_PASSWORD: {{ .Values.mysql.password | quote }}

  DB_ROOT_PASSWORD: "root"
