apiVersion: v1
kind: Service
metadata:
  name: cache-app
  namespace: cache-app
  labels:
    app: cache-app
spec:
  selector:
    app: cache-app
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort   # use LoadBalancer if on a cloud provider (GKE, EKS, AKS)
