apiVersion: v2
name: cache-app-v3
description: Cache App V3 Helm Chart
type: application
version: 0.1.0
appVersion: "1.0"

icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/helm.svg