  namespace: cache-app-v3
  activeProfiles: k8s

  kafka:
    enabled: true
    name: kafka-v3
    version: 4.2.0
    namespace: strimzi-system

    bootstrapServers: kafka-v3-kafka-bootstrap:9092

    topics:
      customerTopic: cache-app-v3.customer_topic
      customerProtoTopic: cache-app-v3.customer_proto

  kafkaConnect:
    enabled: true
    name: kafka-connect

    image: kafka-connect-debezium:1.0.1

    groupId: cache-app-v3-connect-cluster

    configStorageTopic: cache-app-v3-connect-configs
    offsetStorageTopic: cache-app-v3-connect-offsets
    statusStorageTopic: cache-app-v3-connect-status

  debezium:
    enabled: true
    mysqlOutboxServerId: 284054
    mysqlProtoServerId: 284055

  customerService:
    enabled: true
    name: customer-service
    image: customer-service:0.0.5

    replicas: 1

    service:
      type: NodePort
      port: 8080
      targetPort: 8080
      nodePort: 31101

  mysql:
    enabled: true
    hostname: customer-mysql
    image: mysql:8.0

    replicas: 1

    port: 3306
    database: customer_db
    username: user
    password: password
    rootPassword: root

    storage: 256Mi

  auditService:
    enabled: true
    name: audit-service
    image: audit-service:0.0.5

    replicas: 1

    service:
      type: NodePort
      port: 8080
      targetPort: 8080
      nodePort: 31102

  postgres:
    enabled: true
    hostname: audit-postgres
    image: postgres:15

    replicas: 1

    port: 5432
    database: audit_db
    username: postgres
    password: postgres

    storage: 256Mi

  kafkaUi:
    enabled: true
    name: kafka-ui
    image: provectuslabs/kafka-ui:latest

    replicas: 1

    clusterName: local

    service:
      type: NodePort
      port: 8080
      targetPort: 8080
      nodePort: 32180

  redis:

   name: customer-redis
   image: redis:7-alpine

   replicas: 1
   port: 6379

  syncWaves:
    mysql: "2"
    mysqlGrant: "3"
    postgres: "4"
    redis: "9"
    kafkaUi: "10"

    auditServiceConfigMap: "1"
    auditServiceSecret: "1"
    auditService: "12"
    auditServiceService: "12"

    customerServiceConfigMap: "1"
    customerServiceSecret: "1"
    customerService: "11"
    customerServiceService: "11"

    kafkaNodePool: "5"
    kafka: "6"
    kafkaConnect: "7"
    kafkaTopics: "8"
    kafkaConnectors: "9"

