apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-postgres
  namespace: cache-app
  labels:
    app: audit-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-postgres
  template:
    metadata:
      labels:
        app: audit-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: audit_db

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: customer-audit-service-secret
                  key: DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-audit-service-secret
                  key: DB_PASSWORD

          args:
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "max_replication_slots=4"
            - "-c"
            - "max_wal_senders=4"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: "384Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: audit-postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: audit-postgres
  namespace: cache-app
spec:
  selector:
    app: audit-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-postgres-pvc
  namespace: cache-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi