apiVersion: v1
kind: Secret
metadata:
  name: debezium-connector-secret
  namespace: strimzi-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  DB_USERNAME: user
  DB_PASSWORD: password