apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: customer-topic
  namespace: strimzi-system
  annotations:
    argocd.argoproj.io/sync-wave: "7"

  labels:
    strimzi.io/cluster: kafka

spec:
  topicName: customer_topic
  partitions: 1
  replicas: 1